import type { CSSProperties } from "react";
import type { InferenceResult } from "@/lib/types";

/** Theme id for debugging / transitions — derived from inference copy, not user-controlled. */
export type VibeThemeId =
  | "default"
  | "calm"
  | "energetic"
  | "melancholy"
  | "cozy"
  | "stormy"
  | "bright"
  | "night"
  | "focus"
  | "romantic"
  | "playful";

export type VibeTheme = {
  id: VibeThemeId;
  /** Flat CSS custom properties for the shell + session UI */
  vars: CSSProperties;
};

function corpus(r: InferenceResult): string {
  return [
    r.mood_label,
    r.playlist_vibe,
    r.playlist_title,
    r.weather_metaphor,
    r.notification_line,
    r.deezer_search_query,
    r.moment_arc,
  ]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();
}

/** Stronger signals first when scores tie */
const TIE_ORDER: VibeThemeId[] = [
  "stormy",
  "melancholy",
  "night",
  "energetic",
  "playful",
  "romantic",
  "cozy",
  "bright",
  "focus",
  "calm",
  "default",
];

const KEYWORDS: Record<Exclude<VibeThemeId, "default">, readonly string[]> = {
  calm: ["calm", "peace", "rest", "gentle", "soft", "quiet", "ease", "zen", "still", "breathe"],
  energetic: ["energy", "pump", "hype", "party", "loud", "upbeat", "dance", "club", "fast", "rush"],
  melancholy: ["melanch", "sad", "blue", "nostalg", "wistful", "lonely", "grief", "heavy heart"],
  cozy: ["cozy", "warm", "blanket", "coffee", "home", "comfort", "sweater", "fireplace"],
  stormy: ["storm", "rain", "grey", "gray", "thunder", "wind", "cloud", "drizzle", "fog"],
  bright: ["bright", "sun", "summer", "shine", "golden", "morning", "daylight", "clear sky"],
  night: ["night", "late", "midnight", "moon", "neon", "city lights", "after dark", "insomnia"],
  focus: ["focus", "study", "deep", "flow", "grind", "work", "deadline", "locked in"],
  romantic: ["romantic", "love", "crush", "date", "heart", "slow dance", "intimate"],
  playful: ["playful", "fun", "silly", "goofy", "lightheart", "whims", "bounce"],
};

function pickThemeId(text: string): VibeThemeId {
  let best: VibeThemeId = "default";
  let bestScore = -1;
  const entries = Object.entries(KEYWORDS) as [Exclude<VibeThemeId, "default">, readonly string[]][];
  for (const [id, words] of entries) {
    let score = 0;
    for (const w of words) {
      if (text.includes(w)) score += 1;
    }
    if (score === 0) continue;
    if (score > bestScore) {
      bestScore = score;
      best = id;
    } else if (score === bestScore) {
      const ni = TIE_ORDER.indexOf(id);
      const nb = TIE_ORDER.indexOf(best);
      if (ni !== -1 && nb !== -1 && ni < nb) best = id;
    }
  }
  if (bestScore <= 0) return "default";
  return best;
}

/** Small aesthetic modifiers — stay subtle so brutalist chrome stays readable */
type Accent = {
  saturate: string;
  hueRotate: string;
  radiusBump: string;
};

const ACCENTS: Record<VibeThemeId, Accent> = {
  default: { saturate: "1", hueRotate: "0deg", radiusBump: "1rem" },
  calm: { saturate: "1.03", hueRotate: "-6deg", radiusBump: "1.35rem" },
  energetic: { saturate: "1.12", hueRotate: "12deg", radiusBump: "0.95rem" },
  melancholy: { saturate: "0.94", hueRotate: "-14deg", radiusBump: "1.2rem" },
  cozy: { saturate: "1.06", hueRotate: "8deg", radiusBump: "1.25rem" },
  stormy: { saturate: "0.88", hueRotate: "-18deg", radiusBump: "1rem" },
  bright: { saturate: "1.1", hueRotate: "6deg", radiusBump: "1.1rem" },
  night: { saturate: "1.05", hueRotate: "22deg", radiusBump: "1rem" },
  focus: { saturate: "0.96", hueRotate: "-8deg", radiusBump: "0.85rem" },
  romantic: { saturate: "1.07", hueRotate: "4deg", radiusBump: "1.4rem" },
  playful: { saturate: "1.14", hueRotate: "18deg", radiusBump: "1.15rem" },
};

type Patch = Partial<Record<keyof typeof BASE_VARS, string>>;

const BASE_VARS = {
  "--vc-page-bg": "#fff8f0",
  "--vc-radial": "rgba(232, 93, 142, 0.08)",
  "--vc-radial-2": "rgba(255, 212, 120, 0.06)",
  "--vc-accent": "#e85d8e",
  "--vc-player-surface": "#faf5eb",
  "--vc-player-badge": "#fff4d6",
  "--vc-player-gear-hover": "#fff4d6",
  "--vc-player-cover-fallback": "#fff4d6",
  "--vc-player-skip": "#dffaf0",
  "--vc-player-play": "#ffb8d9",
  "--vc-progress": "#e85d8e",
  "--vc-wave": "#e85d8e",
  "--vc-chip-mood": "#fff4d6",
  "--vc-chip-confidence": "#e8deff",
  "--vc-track-row": "#dffaf0",
  "--vc-track-active": "#c8f5e5",
  "--vc-sidebar-now": "#ffd6ea",
  "--vc-sidebar-details-inner": "#fff0f7",
  "--vc-sidebar-suggested": "#c9ecff",
  "--vc-sidebar-nudge": "#fff4b8",
  "--vc-reshuffle": "#e8deff",
  "--vc-reshuffle-hover": "#ddd4ff",
  "--vc-empty-tracks": "#faf5eb",
  "--vc-re-read-hover": "#faf5eb",
  "--vc-footer": "#faf5eb",
  "--vc-link-hover": "#e85d8e",
  "--vc-toast-shell": "#f4f0ff",
  "--vc-toast-footer": "#faf5eb",
  "--vc-toast-play": "#ffb8d9",
  "--vc-toast-play-hover": "#ffa3cf",
  "--vc-toast-apple": "#c8f5e5",
  "--vc-toast-apple-hover": "#b3efd9",
  "--vc-toast-dismiss-hover": "#fff4d6",
  "--vc-toast-os": "#e8fcff",
  "--vc-dot-a": "#ffd6ea",
  "--vc-dot-b": "#fff4d6",
  "--vc-dot-c": "#d8f8ee",
} as const;

const PATCHES: Record<VibeThemeId, Patch> = {
  default: {},
  calm: {
    "--vc-page-bg": "#f4faf7",
    "--vc-radial": "rgba(91, 138, 122, 0.12)",
    "--vc-radial-2": "rgba(180, 214, 232, 0.08)",
    "--vc-accent": "#5b8a7a",
    "--vc-player-surface": "#f2faf6",
    "--vc-player-badge": "#e6f4ef",
    "--vc-player-gear-hover": "#dff5ea",
    "--vc-player-cover-fallback": "#e8f5f0",
    "--vc-player-skip": "#dcefeb",
    "--vc-player-play": "#bfe8d9",
    "--vc-progress": "#4a7d6f",
    "--vc-wave": "#6aa896",
    "--vc-chip-mood": "#e6f4ef",
    "--vc-chip-confidence": "#d6ecff",
    "--vc-track-row": "#e8f5f0",
    "--vc-track-active": "#cdeee4",
    "--vc-sidebar-now": "#d9f0e8",
    "--vc-sidebar-details-inner": "#eef8f5",
    "--vc-sidebar-suggested": "#cfe8f5",
    "--vc-sidebar-nudge": "#f2efd9",
    "--vc-reshuffle": "#d6ecff",
    "--vc-reshuffle-hover": "#c4e3ff",
    "--vc-empty-tracks": "#f2faf6",
    "--vc-re-read-hover": "#eef7f3",
    "--vc-footer": "#eef7f3",
    "--vc-link-hover": "#3d6b5c",
    "--vc-toast-shell": "#eaf6f2",
    "--vc-toast-footer": "#f2faf6",
    "--vc-toast-play": "#bfe8d9",
    "--vc-toast-play-hover": "#a8dfc9",
    "--vc-toast-apple": "#c9ecff",
    "--vc-toast-apple-hover": "#b3e0fb",
    "--vc-toast-dismiss-hover": "#e6f4ef",
    "--vc-toast-os": "#dff6ff",
    "--vc-dot-a": "#bfe8d9",
    "--vc-dot-b": "#d6ecff",
    "--vc-dot-c": "#cfe8f5",
  },
  energetic: {
    "--vc-page-bg": "#fff5f0",
    "--vc-radial": "rgba(255, 94, 58, 0.14)",
    "--vc-radial-2": "rgba(255, 200, 42, 0.1)",
    "--vc-accent": "#ff3d6c",
    "--vc-player-surface": "#fff0e8",
    "--vc-player-badge": "#ffe566",
    "--vc-player-gear-hover": "#ffe08a",
    "--vc-player-cover-fallback": "#ffe566",
    "--vc-player-skip": "#ffd4ba",
    "--vc-player-play": "#ff7ab8",
    "--vc-progress": "#ff3d6c",
    "--vc-wave": "#ff5c8a",
    "--vc-chip-mood": "#ffe566",
    "--vc-chip-confidence": "#ffd4f4",
    "--vc-track-row": "#ffe8dc",
    "--vc-track-active": "#ffc9b8",
    "--vc-sidebar-now": "#ffc9d9",
    "--vc-sidebar-details-inner": "#fff0f5",
    "--vc-sidebar-suggested": "#b8e8ff",
    "--vc-sidebar-nudge": "#fff59a",
    "--vc-reshuffle": "#ffd4f4",
    "--vc-reshuffle-hover": "#ffb8e8",
    "--vc-empty-tracks": "#fff0e8",
    "--vc-re-read-hover": "#ffe8dc",
    "--vc-footer": "#fff0e8",
    "--vc-link-hover": "#e02055",
    "--vc-toast-shell": "#ffe8f2",
    "--vc-toast-footer": "#fff0e8",
    "--vc-toast-play": "#ff7ab8",
    "--vc-toast-play-hover": "#ff5ca5",
    "--vc-toast-apple": "#a8f5e0",
    "--vc-toast-apple-hover": "#8eefd4",
    "--vc-toast-dismiss-hover": "#ffe566",
    "--vc-toast-os": "#d4f8ff",
    "--vc-dot-a": "#ff7ab8",
    "--vc-dot-b": "#ffe566",
    "--vc-dot-c": "#a8f5e0",
  },
  melancholy: {
    "--vc-page-bg": "#eef1f8",
    "--vc-radial": "rgba(107, 127, 215, 0.12)",
    "--vc-radial-2": "rgba(120, 140, 180, 0.09)",
    "--vc-accent": "#6b7fd7",
    "--vc-player-surface": "#e9ecf6",
    "--vc-player-badge": "#dde2f2",
    "--vc-player-gear-hover": "#d5daf0",
    "--vc-player-cover-fallback": "#dde2f2",
    "--vc-player-skip": "#d4dcf5",
    "--vc-player-play": "#c4b5e8",
    "--vc-progress": "#5a6bc4",
    "--vc-wave": "#8b9ae0",
    "--vc-chip-mood": "#dde2f2",
    "--vc-chip-confidence": "#e0d4f7",
    "--vc-track-row": "#e0e5f5",
    "--vc-track-active": "#c9d2f0",
    "--vc-sidebar-now": "#ddd6f5",
    "--vc-sidebar-details-inner": "#eceaf8",
    "--vc-sidebar-suggested": "#c5daf8",
    "--vc-sidebar-nudge": "#e8e2d4",
    "--vc-reshuffle": "#e0d4f7",
    "--vc-reshuffle-hover": "#d1c2f2",
    "--vc-empty-tracks": "#e9ecf6",
    "--vc-re-read-hover": "#e2e6f5",
    "--vc-footer": "#e9ecf6",
    "--vc-link-hover": "#4a56b0",
    "--vc-toast-shell": "#e6e9f8",
    "--vc-toast-footer": "#e9ecf6",
    "--vc-toast-play": "#c4b5e8",
    "--vc-toast-play-hover": "#b39edf",
    "--vc-toast-apple": "#b8e0e8",
    "--vc-toast-apple-hover": "#9fd4df",
    "--vc-toast-dismiss-hover": "#dde2f2",
    "--vc-toast-os": "#d8eef8",
    "--vc-dot-a": "#c4b5e8",
    "--vc-dot-b": "#dde2f2",
    "--vc-dot-c": "#b8e0e8",
  },
  cozy: {
    "--vc-page-bg": "#fff6ec",
    "--vc-radial": "rgba(196, 92, 38, 0.1)",
    "--vc-radial-2": "rgba(244, 162, 89, 0.09)",
    "--vc-accent": "#c45c26",
    "--vc-player-surface": "#faf1e6",
    "--vc-player-badge": "#fce4c4",
    "--vc-player-gear-hover": "#fad9ad",
    "--vc-player-cover-fallback": "#fce4c4",
    "--vc-player-skip": "#f5dcc8",
    "--vc-player-play": "#f4a259",
    "--vc-progress": "#c45c26",
    "--vc-wave": "#e07a3c",
    "--vc-chip-mood": "#fce4c4",
    "--vc-chip-confidence": "#e8ddd4",
    "--vc-track-row": "#f5e6d6",
    "--vc-track-active": "#edc9a8",
    "--vc-sidebar-now": "#ffd9c4",
    "--vc-sidebar-details-inner": "#fff2e8",
    "--vc-sidebar-suggested": "#d4e8f7",
    "--vc-sidebar-nudge": "#ffe08a",
    "--vc-reshuffle": "#e8ddd4",
    "--vc-reshuffle-hover": "#dcd0c4",
    "--vc-empty-tracks": "#faf1e6",
    "--vc-re-read-hover": "#f5e6d6",
    "--vc-footer": "#faf1e6",
    "--vc-link-hover": "#a34418",
    "--vc-toast-shell": "#fceee3",
    "--vc-toast-footer": "#faf1e6",
    "--vc-toast-play": "#f4a259",
    "--vc-toast-play-hover": "#ef8f3d",
    "--vc-toast-apple": "#c8ecd9",
    "--vc-toast-apple-hover": "#b0e3ca",
    "--vc-toast-dismiss-hover": "#fce4c4",
    "--vc-toast-os": "#e5f8fc",
    "--vc-dot-a": "#f4a259",
    "--vc-dot-b": "#fce4c4",
    "--vc-dot-c": "#c8ecd9",
  },
  stormy: {
    "--vc-page-bg": "#eef2f6",
    "--vc-radial": "rgba(74, 111, 165, 0.11)",
    "--vc-radial-2": "rgba(90, 110, 130, 0.08)",
    "--vc-accent": "#4a6fa5",
    "--vc-player-surface": "#e8ecf2",
    "--vc-player-badge": "#dce4ee",
    "--vc-player-gear-hover": "#d3dce8",
    "--vc-player-cover-fallback": "#dce4ee",
    "--vc-player-skip": "#cfd9e8",
    "--vc-player-play": "#9eb8d8",
    "--vc-progress": "#4a6fa5",
    "--vc-wave": "#7a96bf",
    "--vc-chip-mood": "#dce4ee",
    "--vc-chip-confidence": "#d4e0f0",
    "--vc-track-row": "#dfe6f0",
    "--vc-track-active": "#c5d4e8",
    "--vc-sidebar-now": "#d4dde8",
    "--vc-sidebar-details-inner": "#e8ecf4",
    "--vc-sidebar-suggested": "#b8d4f0",
    "--vc-sidebar-nudge": "#e2dfd6",
    "--vc-reshuffle": "#d4e0f0",
    "--vc-reshuffle-hover": "#c2d2ea",
    "--vc-empty-tracks": "#e8ecf2",
    "--vc-re-read-hover": "#e2e8f0",
    "--vc-footer": "#e8ecf2",
    "--vc-link-hover": "#345a8c",
    "--vc-toast-shell": "#e4eaf2",
    "--vc-toast-footer": "#e8ecf2",
    "--vc-toast-play": "#9eb8d8",
    "--vc-toast-play-hover": "#89a8cf",
    "--vc-toast-apple": "#b8dfd5",
    "--vc-toast-apple-hover": "#a0d4c8",
    "--vc-toast-dismiss-hover": "#dce4ee",
    "--vc-toast-os": "#d8eef5",
    "--vc-dot-a": "#9eb8d8",
    "--vc-dot-b": "#dce4ee",
    "--vc-dot-c": "#b8dfd5",
  },
  bright: {
    "--vc-page-bg": "#fffef8",
    "--vc-radial": "rgba(255, 214, 90, 0.14)",
    "--vc-radial-2": "rgba(0, 180, 216, 0.07)",
    "--vc-accent": "#00b4d8",
    "--vc-player-surface": "#fffbeb",
    "--vc-player-badge": "#fff59a",
    "--vc-player-gear-hover": "#fff178",
    "--vc-player-cover-fallback": "#fff59a",
    "--vc-player-skip": "#d4f4ff",
    "--vc-player-play": "#90e0ef",
    "--vc-progress": "#00b4d8",
    "--vc-wave": "#48cae4",
    "--vc-chip-mood": "#fff59a",
    "--vc-chip-confidence": "#caf0f8",
    "--vc-track-row": "#e8fbff",
    "--vc-track-active": "#caf0f8",
    "--vc-sidebar-now": "#fff2b8",
    "--vc-sidebar-details-inner": "#fffdf0",
    "--vc-sidebar-suggested": "#ade8f4",
    "--vc-sidebar-nudge": "#fff178",
    "--vc-reshuffle": "#caf0f8",
    "--vc-reshuffle-hover": "#b3e8f5",
    "--vc-empty-tracks": "#fffbeb",
    "--vc-re-read-hover": "#fff8dc",
    "--vc-footer": "#fffbeb",
    "--vc-link-hover": "#0096c7",
    "--vc-toast-shell": "#e8fbff",
    "--vc-toast-footer": "#fffbeb",
    "--vc-toast-play": "#90e0ef",
    "--vc-toast-play-hover": "#6ed6ea",
    "--vc-toast-apple": "#b5f5c8",
    "--vc-toast-apple-hover": "#99f0b4",
    "--vc-toast-dismiss-hover": "#fff59a",
    "--vc-toast-os": "#dffbfd",
    "--vc-dot-a": "#90e0ef",
    "--vc-dot-b": "#fff59a",
    "--vc-dot-c": "#b5f5c8",
  },
  night: {
    "--vc-page-bg": "#f2eff8",
    "--vc-radial": "rgba(124, 58, 237, 0.1)",
    "--vc-radial-2": "rgba(56, 189, 248, 0.08)",
    "--vc-accent": "#7c3aed",
    "--vc-player-surface": "#ede9f7",
    "--vc-player-badge": "#e4dcff",
    "--vc-player-gear-hover": "#dbd0ff",
    "--vc-player-cover-fallback": "#e4dcff",
    "--vc-player-skip": "#d4e8ff",
    "--vc-player-play": "#c4b5fd",
    "--vc-progress": "#7c3aed",
    "--vc-wave": "#a78bfa",
    "--vc-chip-mood": "#e4dcff",
    "--vc-chip-confidence": "#d8f3ff",
    "--vc-track-row": "#e2e8ff",
    "--vc-track-active": "#c7d2fe",
    "--vc-sidebar-now": "#ddd6fe",
    "--vc-sidebar-details-inner": "#f3f0ff",
    "--vc-sidebar-suggested": "#bae6fd",
    "--vc-sidebar-nudge": "#fef3c7",
    "--vc-reshuffle": "#d8f3ff",
    "--vc-reshuffle-hover": "#c4ebff",
    "--vc-empty-tracks": "#ede9f7",
    "--vc-re-read-hover": "#e6e4f7",
    "--vc-footer": "#ede9f7",
    "--vc-link-hover": "#6d28d9",
    "--vc-toast-shell": "#eae4ff",
    "--vc-toast-footer": "#ede9f7",
    "--vc-toast-play": "#c4b5fd",
    "--vc-toast-play-hover": "#a78bfa",
    "--vc-toast-apple": "#a7f3d0",
    "--vc-toast-apple-hover": "#86efac",
    "--vc-toast-dismiss-hover": "#e4dcff",
    "--vc-toast-os": "#cffafe",
    "--vc-dot-a": "#c4b5fd",
    "--vc-dot-b": "#bae6fd",
    "--vc-dot-c": "#a7f3d0",
  },
  focus: {
    "--vc-page-bg": "#f5f9fa",
    "--vc-radial": "rgba(61, 90, 128, 0.09)",
    "--vc-radial-2": "rgba(168, 200, 212, 0.07)",
    "--vc-accent": "#3d5a80",
    "--vc-player-surface": "#eef3f6",
    "--vc-player-badge": "#e2ebf0",
    "--vc-player-gear-hover": "#d9e5ec",
    "--vc-player-cover-fallback": "#e2ebf0",
    "--vc-player-skip": "#d5e8e4",
    "--vc-player-play": "#98c1d9",
    "--vc-progress": "#3d5a80",
    "--vc-wave": "#6b8cae",
    "--vc-chip-mood": "#e2ebf0",
    "--vc-chip-confidence": "#dde8f5",
    "--vc-track-row": "#e4eef2",
    "--vc-track-active": "#c8dce8",
    "--vc-sidebar-now": "#d4e5ed",
    "--vc-sidebar-details-inner": "#eef4f7",
    "--vc-sidebar-suggested": "#bee3f8",
    "--vc-sidebar-nudge": "#f0ead2",
    "--vc-reshuffle": "#dde8f5",
    "--vc-reshuffle-hover": "#ccdff0",
    "--vc-empty-tracks": "#eef3f6",
    "--vc-re-read-hover": "#e8f0f4",
    "--vc-footer": "#eef3f6",
    "--vc-link-hover": "#2d4666",
    "--vc-toast-shell": "#e8f0f5",
    "--vc-toast-footer": "#eef3f6",
    "--vc-toast-play": "#98c1d9",
    "--vc-toast-play-hover": "#7eb3cf",
    "--vc-toast-apple": "#b8e0d4",
    "--vc-toast-apple-hover": "#9fd4c4",
    "--vc-toast-dismiss-hover": "#e2ebf0",
    "--vc-toast-os": "#e0f7fa",
    "--vc-dot-a": "#98c1d9",
    "--vc-dot-b": "#e2ebf0",
    "--vc-dot-c": "#b8e0d4",
  },
  romantic: {
    "--vc-page-bg": "#fff5f8",
    "--vc-radial": "rgba(214, 51, 132, 0.09)",
    "--vc-radial-2": "rgba(255, 182, 193, 0.1)",
    "--vc-accent": "#d63384",
    "--vc-player-surface": "#fff0f5",
    "--vc-player-badge": "#ffd6e8",
    "--vc-player-gear-hover": "#ffc9df",
    "--vc-player-cover-fallback": "#ffd6e8",
    "--vc-player-skip": "#fce4ec",
    "--vc-player-play": "#ff8fab",
    "--vc-progress": "#d63384",
    "--vc-wave": "#f06292",
    "--vc-chip-mood": "#ffd6e8",
    "--vc-chip-confidence": "#f3e8ff",
    "--vc-track-row": "#fce7ef",
    "--vc-track-active": "#f8bbd9",
    "--vc-sidebar-now": "#ffc2d4",
    "--vc-sidebar-details-inner": "#fff5f9",
    "--vc-sidebar-suggested": "#d0f4ff",
    "--vc-sidebar-nudge": "#ffe5ec",
    "--vc-reshuffle": "#f3e8ff",
    "--vc-reshuffle-hover": "#e9d8ff",
    "--vc-empty-tracks": "#fff0f5",
    "--vc-re-read-hover": "#fce7ef",
    "--vc-footer": "#fff0f5",
    "--vc-link-hover": "#b02a5e",
    "--vc-toast-shell": "#ffe4f0",
    "--vc-toast-footer": "#fff0f5",
    "--vc-toast-play": "#ff8fab",
    "--vc-toast-play-hover": "#ff6f9a",
    "--vc-toast-apple": "#c8f7dc",
    "--vc-toast-apple-hover": "#aaf0cb",
    "--vc-toast-dismiss-hover": "#ffd6e8",
    "--vc-toast-os": "#e8faff",
    "--vc-dot-a": "#ff8fab",
    "--vc-dot-b": "#ffd6e8",
    "--vc-dot-c": "#c8f7dc",
  },
  playful: {
    "--vc-page-bg": "#f8fff5",
    "--vc-radial": "rgba(157, 78, 221, 0.09)",
    "--vc-radial-2": "rgba(72, 199, 142, 0.09)",
    "--vc-accent": "#9d4edd",
    "--vc-player-surface": "#f3fff8",
    "--vc-player-badge": "#e0ffc8",
    "--vc-player-gear-hover": "#d4ffb5",
    "--vc-player-cover-fallback": "#e0ffc8",
    "--vc-player-skip": "#d8f3dc",
    "--vc-player-play": "#ff9ecd",
    "--vc-progress": "#9d4edd",
    "--vc-wave": "#c77dff",
    "--vc-chip-mood": "#e0ffc8",
    "--vc-chip-confidence": "#ffd6ff",
    "--vc-track-row": "#e8ffe8",
    "--vc-track-active": "#caffbf",
    "--vc-sidebar-now": "#ffd6ff",
    "--vc-sidebar-details-inner": "#faf5ff",
    "--vc-sidebar-suggested": "#9bf6ff",
    "--vc-sidebar-nudge": "#fff59a",
    "--vc-reshuffle": "#ffd6ff",
    "--vc-reshuffle-hover": "#ffb8f5",
    "--vc-empty-tracks": "#f3fff8",
    "--vc-re-read-hover": "#e8ffe8",
    "--vc-footer": "#f3fff8",
    "--vc-link-hover": "#7b2cbf",
    "--vc-toast-shell": "#f5e6ff",
    "--vc-toast-footer": "#f3fff8",
    "--vc-toast-play": "#ff9ecd",
    "--vc-toast-play-hover": "#ff7eb8",
    "--vc-toast-apple": "#b5f8cc",
    "--vc-toast-apple-hover": "#95f5b8",
    "--vc-toast-dismiss-hover": "#e0ffc8",
    "--vc-toast-os": "#e0fbff",
    "--vc-dot-a": "#ff9ecd",
    "--vc-dot-b": "#e0ffc8",
    "--vc-dot-c": "#9bf6ff",
  },
};

function mergeVars(id: VibeThemeId): Record<string, string> {
  const base = { ...BASE_VARS } as Record<string, string>;
  const patch = PATCHES[id];
  for (const k of Object.keys(patch)) {
    const key = k as keyof typeof BASE_VARS;
    const v = patch[key];
    if (v !== undefined) base[key] = v;
  }
  const a = ACCENTS[id];
  base["--vc-saturate"] = a.saturate;
  base["--vc-hue-rotate"] = a.hueRotate;
  base["--vc-radius-bump"] = a.radiusBump;
  return base;
}

export function resolveVibeTheme(inference: InferenceResult): VibeTheme {
  let id = pickThemeId(corpus(inference));
  if (inference.safety.distress_hint) {
    id = "calm";
  }
  const vars = mergeVars(id) as unknown as CSSProperties;
  return { id, vars };
}
